version: '3'

services:
  dumpsterfire:
    image: php:8.4-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: /bin/bash -c "a2enmod rewrite && apache2-foreground"
